name: OS versions

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  basic-job:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Run a one-line script
        run: echo "Hello, world!
